"""empty message

Revision ID: 032f7603a04f
Revises: e8267c01edfe
Create Date: 2020-12-12 21:54:41.412500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032f7603a04f'
down_revision = 'e8267c01edfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siswa', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'user', 'siswa', ['user_name'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('siswa', 'email')
    # ### end Alembic commands ###
