"""empty message

Revision ID: 3423d9819cc9
Revises: e8267c01edfe
Create Date: 2020-12-13 11:20:32.025060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3423d9819cc9'
down_revision = 'e8267c01edfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pelajaran', sa.Column('id_siswa', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pelajaran', 'siswa', ['id_siswa'], ['id'])
    op.drop_index('user_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_name', 'user', ['user_name'], unique=True)
    op.drop_constraint(None, 'pelajaran', type_='foreignkey')
    op.drop_column('pelajaran', 'id_siswa')
    # ### end Alembic commands ###
