"""empty message

Revision ID: 5a3c20c82279
Revises: 5d463576658b
Create Date: 2020-12-13 19:45:24.337660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a3c20c82279'
down_revision = '5d463576658b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pelajaran_ibfk_1', 'pelajaran', type_='foreignkey')
    op.drop_column('pelajaran', 'id_siswa')
    op.add_column('siswa', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'siswa', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'siswa', type_='unique')
    op.drop_column('siswa', 'email')
    op.add_column('pelajaran', sa.Column('id_siswa', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('pelajaran_ibfk_1', 'pelajaran', 'siswa', ['id_siswa'], ['id'])
    # ### end Alembic commands ###
